services:
  ubuntu:
    container_name: database-ubuntu-app
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true # Required for Docker-in-Docker
    tty: true
    stdin_open: true
    volumes:
      - ./:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lion

  mysql:
    image: mysql
    container_name: database-ubuntu-mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_DATABASE: lion_database
        MYSQL_PASSWORD: lion
        MYSQL_ROOT_PASSWORD: lion
    volumes:
        - mysql_data:/var/lib/mysql
    networks:
        - lion

  postgres:
    image: postgres
    container_name: database-ubuntu-postgres
    ports:
        - 5432:5432
    environment:
        POSTGRES_DB: lion_database
        POSTGRES_USER: root
        POSTGRES_PASSWORD: lion
    volumes:
        - postgres_data:/var/lib/postgresql
    networks:
        - lion

volumes:
  mysql_data:
  postgres_data:

networks:
  lion:
    driver: bridge